### ISSUE TITLE
orientation issue

### ISSUE THREAD

**Issue by mythodeia** [wwdc14/HySideScrollingImagePicker#5]
Hello,
there are issues when rotating the device in landscape mode. you can test like this:
- open the app,
- open the imagepicker,
- rotate the simulator/device in landscape while the picker is still open,
- the view behind rotates fine but the picker does not. Plus the buttons cannot be tapped.

another scenario is this:
- open the app,
- open the imagepicker,
- rotate the simulator/device without opening anything yet,
- tap to open the imagepicker and you will see the screen below:

![issue2](https://cloud.githubusercontent.com/assets/1748458/9809163/a4eb26e6-586e-11e5-9a6a-c71b419787f6.png)

**Comment by wwdc14yh** [comment]
Thank you very much involved in testing

it doesn't  support   rotation 
 i will fix your questions if I have free time

**Comment by mythodeia** [comment]
:+1:

**Comment by wwdc14yh** [comment]
Made support for screen rotation

**Comment by wwdc14yh** [comment]
Welcome to Test

**Comment by mythodeia** [comment]
@wwdc14 i tried it and still have the same errors. from your latest commit i cannot see any changes regarding the orientation issue.

**Comment by wwdc14yh** [comment]
My local Git problems, and did not submit up code is rolled back ...

**Comment by wwdc14yh** [comment]
I'm too rewriting code

**Comment by wwdc14yh** [comment]
This bug has been fixed

**Comment by wwdc14yh** [comment]
You can now download the latest demo

**Comment by mythodeia** [comment]
excellent. :+1:  thanks

**Comment by wwdc14yh** [comment]
You're welcome, thank you very much test,
