### ISSUE TITLE
multipleselection small issue

### ISSUE THREAD

**Issue by mythodeia** [wwdc14/HySideScrollingImagePicker#6]
now the demo has :
`hy.isMultipleSelection = false;`
for the ImagePicker

if i change it to 
`hy.isMultipleSelection = YES;`
the picker allows only 1 selection. If you change it to NO it allows multiple.

this can be fixed in method
`- (void)toggleSelectionAtIndexPath:(NSIndexPath *)indexPath`
change this:
`if (!_isMultipleSelection) {`
to this
`if (isMultipleSelection) {`

thanks again for the library :+1:

**Comment by wwdc14yh** [comment]
Thanks for advice

**Comment by wwdc14yh** [comment]
But I think I should have a rest

**Comment by wwdc14yh** [comment]
Because I was in China

**Comment by mythodeia** [comment]
no worries.Its a small fix. You can do it whenever you want. thanks for the support

**Comment by wwdc14yh** [comment]
Ok ,I was changing for the better!

**Comment by mythodeia** [comment]
:+1: have a great night
